---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dmutreja/cpi-release-build-env
    tag: "latest"
inputs:
  - name: cpi-release
  - name: version-semver
outputs:
  - name: artifacts
run:
  path: cpi-release/ci/tasks/build-final-release.sh
