---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker-repo-name))/oci-cli
    tag: "latest"
inputs:
  - name: artifacts
  - name: cpi-release
run:
  path: cpi-release/ci/tasks/upload-release-artifacts.sh
params:
  tenancy: replace-me
  user:    replace-me
  fingerprint: replace-me
  apikey:  replace-me
  region: replace-me
  namespace: replace-me
  bucket:  replace-me
