---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.8.3"
inputs:
  - name: cpi-src
  - name: oci-config
run:
  path: cpi-src/src/github.com/oracle/bosh-oracle-cpi/ci/tasks/oci-tests.sh
